#+TITLE: Clip - Utility to copy image from clipboard to file. 
#+AUTHOR: Caio Rodrigues
#+EMAIL:  caiorss DOT rodrigues AT gmail DOT com 
#+STARTUP: overview

* Clip 
** Overview 

Clip is a self-contained command line utility written in Scala to
extract images from clipboard and save it to a file. It is a module of
[[https://github.com/caiorss/org-wiki][org-wiki]] project.

Motivation: This utility is useful to paste images on Emacs org-mode
and markdown formats like github markdown.

** Usage 

1. Copy an image from clipboard to a file with given name. 

 - =$ java -jar Clip.jar -file /tmp/image.png=

Example:

#+BEGIN_SRC 
$ java -jar ./target/scala-2.11/Clip-assembly-1.0.jar -file /tmp/image.png
file:/tmp/image.png
#+END_SRC

2. Copy an image from clipboard to file with an uuid (automatically
   generated name). 

 - =$ java -jar Clip.jar -uuid /tmp=

Example:

#+BEGIN_SRC 
$ java -jar ./target/scala-2.11/Clip-assembly-1.0.jar -uuid /tmp 
file:/tmp/715dbacb-c6d1-40db-8d91-c90e7217ace8.png
#+END_SRC

** Build 
 
To build it is necessary Scala and Sbt be installed on the system. 

*Build instruction* 

 - Just run =$ make= to build the ubber jar. The output file will be
   ./target/scala-2.11/Clip-assembly-1.0.jar

** Test 

 - =$ make test1=

Copy an image and enter $ make test1. If the app works it will write
the image to the file _clipboard.png_. 



 - =$ make test2= 

Copy an image to 

The output will be like: 

#+BEGIN_SRC 
$ make test2
java -jar ./target/scala-2.11/Clip-assembly-1.0.jar -uuid . 
file:./fba53c12-3f23-4728-9f52-a26a3d285d7c.png
#+END_SRC

** Emacs Client Code 

This emacs command can be used to paste images. The command M-x org-paste-image
ask the user the directory him whichs to paste and then it inserts the
path to the image relative to current directory. If the current
directory is ~/ (/home/dummy) and the the current file is ~/test.org
, if the user chooses to paste the file at directory ~/Pictures it
inserts the path to the crated file ~file:Pictures/acb19f19-31c0-4550-874d-1111aafbb93f.png~.
 

#+BEGIN_SRC elisp 
(defun org-paste-image ()
     (interactive)
     (let* ((dir (read-directory-name "Dir: ")))       
       (insert        
        (shell-command-to-string
         (mapconcat #'identity
                    `("java"
                      "-jar"
                      ,(expand-file-name "~/bin/Clip.jar")
                      "-uuid"
                      ,(file-relative-name dir default-directory)
                      )
                    " "
                    ))))) 
#+END_SRC

** Download Release 

You can download a pre-compilead binary release from: 

 -  https://github.com/caiorss/clip.jar/blob/build/Clip.jar

Or automatically with this bash script: 

#+BEGIN_SRC sh  
  mkdir -p ~/bin && \
      cd ~/bin && \
      curl -O -L https://github.com/caiorss/clip.jar/raw/build/Clip.jar
#+END_SRC


